title: Products

files: false

pages:
  template: products

options: 
  template: false   
  url: false  

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea
    
  text2:
    label: Text 2 Test
    type: textarea
